@startuml UseCasesDetail

rectangle UseCasesDetail {
    package Signup [
    **ID:** UC1
    **Actors:** Visitor
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package Login [
    **ID:** UC2
    **Actors:** Visitor
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package CardVisualization [
    **ID:** UC3
    **Actors:** Visitor
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package CardDetailsVisualizazion [
    **ID:** UC4
    **Actors:** Visitor
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package CardsManagement [
    **ID:** UC5
    **Actors:** User
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package OwnedCardsManagement [
    **ID:** UC6
    **Actors:** User
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package WishedCardsManagement [
    **ID:** UC7
    **Actors:** User
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package DecksManagement [
    **ID:** UC8
    **Actors:** User
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package ProposeExchange [
    **ID:** UC9
    **Actors:** User
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package ExchangeProposalVisualization [
    **ID:** UC10
    **Actors:** User
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package RefuseExchange [
    **ID:** UC11
    **Actors:** User
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package AcceptExchange [
    **ID:** UC12
    **Actors:** User
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]

    package Logout [
    **ID:** UC13
    **Actors:** User
    **Pre-conditions:** Visitor selects one of the available games
    **Main sequence:**
     - step1
     - step2
     - step3
    **Alternative sequence:**
    **Post-conditions:**
    ]
}

@enduml